import json
from pathlib import Path
p=Path(__file__).parent;data=json.loads((p/'master_family.json').read_text())
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Extended family tree</title><style>body{font:16px system-ui;background:#f7f4ec;color:#25352d;margin:0}header{background:#1e4438;color:white;padding:24px clamp(16px,4vw,60px)}h1{margin:0;font-size:30px}header p{margin:6px 0 0;color:#dce9dc}.bar{display:flex;gap:10px;flex-wrap:wrap;padding:20px clamp(16px,4vw,60px)}input,select,button{font:inherit;padding:10px;border:1px solid #bdc9bd;border-radius:8px;background:white}input{min-width:230px;flex:1}button{cursor:pointer;color:#174638}button:hover{background:#e4eee4}main{padding:0 clamp(16px,4vw,60px) 50px}.stats{color:#63746a;margin-bottom:16px}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:12px}.card{border:1px solid #d7ded4;border-left:4px solid #779b76;border-radius:10px;background:white;padding:14px;text-align:left;min-height:70px}.card strong,.card small{display:block}.card small{color:#63746a;margin-top:5px}.tentative{border-left-color:#c89037}.section{margin:28px 0 10px;font-size:19px}.detail{background:#fff;border:1px solid #d7ded4;border-radius:12px;padding:20px;margin:8px 0 25px;max-width:950px}.detail h2{margin:0}.detail p{margin:8px 0}.tag{display:inline-block;background:#ebf2e9;border-radius:20px;padding:4px 9px;margin:3px;font-size:13px}.warn{background:#fff2dc}.back{margin-bottom:12px}details{margin-top:20px}summary{cursor:pointer}a{color:#275d49}</style><header><h1>Extended family tree</h1><p>158 people from seven photographed sheets · select a person to explore connections</p></header><div class="bar"><input id="search" placeholder="Search names, notes, or dates" aria-label="Search people"><select id="source" aria-label="Photo branch"><option value="">All photo branches</option></select><button id="home">Start at oldest generation</button></div><main><div class="stats" id="stats"></div><div id="content"></div></main><script id="family-data" type="application/json">DATA</script><script>
const D=JSON.parse(document.querySelector('#family-data').textContent),people=new Map(D.people.map(p=>[p.id,p])),els={search:document.querySelector('#search'),source:document.querySelector('#source'),content:document.querySelector('#content'),stats:document.querySelector('#stats')};let selected=null;
const sources=[...new Set(D.people.flatMap(p=>p.sources))];sources.forEach(s=>{let o=document.createElement('option');o.value=s;o.textContent=s;els.source.append(o)});
function dates(p){return [p.birth,p.death].some(Boolean)?` (${p.birth||'?'}–${p.death||''})`:''}
function card(id,edge){let p=people.get(id);if(!p)return document.createTextNode('');let b=document.createElement('button');b.className='card'+(edge?.confidence==='tentative'?' tentative':'');b.innerHTML=`<strong></strong><small></small>`;b.querySelector('strong').textContent=p.name;b.querySelector('small').textContent=(p.birth||p.death?`${p.birth||'?'}–${p.death||''} · `:'')+(edge?.confidence==='tentative'?'relationship needs review · ':'')+p.sources[0];b.onclick=()=>{selected=id;els.search.value='';render();window.scrollTo({top:0,behavior:'smooth'})};return b}
function block(title,entries){if(!entries.length)return '';let section=document.createElement('section'),h=document.createElement('h3'),grid=document.createElement('div');h.className='section';h.textContent=title;grid.className='grid';for(let [id,e] of entries)grid.append(card(id,e));section.append(h,grid);return section}
function render(){els.content.replaceChildren();let q=els.search.value.trim().toLowerCase(),s=els.source.value;els.stats.textContent=`${D.people.length} people · ${D.relationships.length} recorded relationships · orange edge means verify against the photo`;
if(q||s||!selected){let matches=D.people.filter(p=>(!s||p.sources.includes(s))&&(!q||[p.name,...(p.aliases||[]),p.birth,p.death,...p.notes].join(' ').toLowerCase().includes(q)));els.content.append(block(q||s?'Matching people':'Founding generation',q||s?matches.map(p=>[p.id]):['john_egan','bridget_kane'].map(id=>[id])));if(!q&&!s){let d=document.createElement('p');d.textContent='Use search or select a person to follow their parents, partners, and children. The photo selector shows what was recorded from each sheet.';els.content.prepend(d)}return}
let p=people.get(selected);if(!p)return;let div=document.createElement('div');div.className='detail';let h=document.createElement('h2');h.textContent=p.name+dates(p);div.append(h);let desc=document.createElement('p');desc.textContent='Sources: '+p.sources.join(' · ');div.append(desc);for(let n of p.notes){let t=document.createElement('p');t.className='tag warn';t.textContent=n;div.append(t)}els.content.append(div);
let parent=D.relationships.filter(e=>e.type==='parent'&&e.to===selected).map(e=>[e.from,e]);let partners=D.relationships.filter(e=>e.type==='partner'&&(e.from===selected||e.to===selected)).map(e=>[e.from===selected?e.to:e.from,e]);let children=D.relationships.filter(e=>e.type==='parent'&&e.from===selected).map(e=>[e.to,e]);for(let [title,items] of [['Parents',parent],['Partners',partners],['Children',children]])els.content.append(block(title,items));let note=document.createElement('details');note.innerHTML='<summary>Photo evidence and relationship notes</summary>';let list=document.createElement('ul');for(let e of D.relationships.filter(e=>e.from===selected||e.to===selected)){let li=document.createElement('li');li.textContent=`${people.get(e.from)?.name} → ${people.get(e.to)?.name}: ${e.type}; ${e.source}; ${e.confidence}${e.note?' — '+e.note:''}`;list.append(li)}note.append(list);els.content.append(note)}
els.search.oninput=()=>render();els.source.onchange=()=>{selected=null;render()};document.querySelector('#home').onclick=()=>{selected='john_egan';els.search.value='';els.source.value='';render()};render();
</script></html>'''
(p/'family_tree.html').write_text(page.replace('DATA',json.dumps(data,ensure_ascii=False).replace('</','<\\/')),encoding='utf8')
